### ISSUE TITLE
Can you change environment in a different region? 

### ISSUE THREAD

**Issue by Zoltango** [MicrosoftDocs/powerapps-docs.hu-hu#2]
I have my production environments in Europe and a preview environment in US. When click "Change" environment link US environment is not offered. In case I created an app in my previre environment "Change" link is not offered as I have no other environment in US region - however there are 3 more environments in my tenant. 
Is it by design? Can I move apps across regions? 

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: b6ef9b3a-5d99-1ca0-0e7f-80c2de740313
* Version Independent ID: 80900e35-c8da-10a1-9902-343e84d823d0
* Content: [Csatlakozás a Common Data Service - PowerApps](https://docs.microsoft.com/hu-hu/powerapps/maker/canvas-apps/connections/connection-common-data-service)
* Content Source: [powerapps-docs/maker/canvas-apps/connections/connection-common-data-service.md](https://github.com/MicrosoftDocs/powerapps-docs.hu-hu/blob/live/powerapps-docs/maker/canvas-apps/connections/connection-common-data-service.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by CeciAc** [comment]
Hello, @Zoltango

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
